### PR TITLE
[WIP] Python examples

### PR DESCRIPTION
**Pull request by alysivji**
@mercedesb 

I've started the process of converting some of the code examples to Python. Wanted to open a PR to see if this format is okay

### CODE REVIEW

**Comment by mercedesb** [comment]
Hi @alysivji! Thanks for this! I'm not going to merge it because I'm actually setting up a separate Django project for my Python code samples. I've already started on it, but thank you for this work. Super helpful!

**Comment by alysivji** [comment]
nw! I think @sisandi has completed a few others

**Comment by mercedesb** [comment]
Oh! I didn't realize there was anyone helping out on this 🙈 I already did a bunch of it, but I'll try to incorporate what I can.

**Comment by alysivji** [comment]
No worries! We only briefly chatted about it. Only spent a few hours. No big deal!

**Pull request closed without merging**
